# Base URL for FPL API
BASE_URL = "https://fantasy.premierleague.com/api/"

# Columns for player profiles
PROFILE_COLS = [
    "full_name",
    "team_name",
    "position",
    "now_cost",
]

# Supported metrics for ranking/analysis
SUPPORTED_METRICS = [
    "assists",
    "bonus",
    "bps",
    "clean_sheets",
    "clean_sheets_per_90",
    "clearances_blocks_interceptions",
    "defensive_contribution",
    "defensive_contribution_per_90",
    "expected_assists",
    "expected_assists_per_90",
    "expected_goal_involvements",
    "expected_goal_involvements_per_90",
    "expected_goals",
    "expected_goals_conceded",
    "expected_goals_conceded_per_90",
    "expected_goals_per_90",
    "form",
    "full_name",
    "goals_conceded",
    "goals_conceded_per_90",
    "goals_scored",
    "minutes",
    "now_cost",
    "own_goals",
    "penalties_missed",
    "penalties_saved",
    "position",
    "recoveries",
    "red_cards",
    "saves",
    "selected_by_percent",
    "starts_per_90",
    "tackles",
    "team_name",
    "total_points",
    "transfers_in",
    "transfers_out",
    "yellow_cards",
]

# Metrics supported for history
SUPPORTED_HISTORY_METRICS = [
    "element",
    "opponent_team_name",
    "total_points",
    "round",
    "minutes",
    "goals_scored",
    "assists",
    "clean_sheets",
    "goals_conceded",
    "own_goals",
    "penalties_saved",
    "penalties_missed",
    "yellow_cards",
    "red_cards",
    "saves",
    "bonus",
    "bps",
    "clearances_blocks_interceptions",
    "recoveries",
    "tackles",
    "defensive_contribution",
    "starts",
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements",
    "expected_goals_conceded",
]
